// flow-typed signature: 39188404c8e9e1bde8ce63bc10664f7c
// flow-typed version: <<STUB>>/markdown_v^0.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown/bin/md2html' {
  declare module.exports: any;
}

declare module 'markdown/lib/index' {
  declare module.exports: any;
}

declare module 'markdown/lib/markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown/bin/md2html.js' {
  declare module.exports: $Exports<'markdown/bin/md2html'>;
}
declare module 'markdown/lib/index.js' {
  declare module.exports: $Exports<'markdown/lib/index'>;
}
declare module 'markdown/lib/markdown.js' {
  declare module.exports: $Exports<'markdown/lib/markdown'>;
}
